# -*- coding: utf-8 -*-
"""03_Preparation_Docking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfNIRWxhX2s96KZF47kPu-znXyAp7eDZ
"""

# %%
import os
import glob
import shutil
import subprocess
import numpy as np
import pandas as pd

# -------- user file paths --------
CANDIDATE_LIBRARY_PATH = "/content/screening_library.csv"   # change if needed

# -------- output / workspace --------
SDF_DIR = "ligands_sdf"
PDBQT_DIR = "ligands_pdbqt"
POSE_DIR = "docked_poses"
PAPER_DIR = "paper_package"

# -------- receptor files --------
PDB_ID = "4BDS"
FULL_PDB = f"{PDB_ID}.pdb"
PROTEIN_CLEAN = "4BDS_chainA_clean.pdb"
NATIVE_PDB = "4BDS_native_ligand.pdb"
RECEPTOR_PREFIX = "4BDS_BuChE_receptor"
RECEPTOR_PDBQT = f"{RECEPTOR_PREFIX}.pdbqt"

# -------- docking settings --------
TOP_N = 30
BOX_SIZE = [20, 20, 20]
EXHAUSTIVENESS = 16

def ensure_clean_folders():
    for folder in [SDF_DIR, PDBQT_DIR, POSE_DIR, PAPER_DIR]:
        if os.path.exists(folder):
            shutil.rmtree(folder)
        os.makedirs(folder, exist_ok=True)

    for f in [
        "ranked_candidates_full_BuChE.csv",
        f"top{TOP_N}_hits_for_docking.csv",
        "docking_results.csv",
        "top10_docked_hits.csv",
    ]:
        if os.path.exists(f):
            os.remove(f)

print("CANDIDATE_LIBRARY_PATH =", CANDIDATE_LIBRARY_PATH)
print("Exists:", os.path.exists(CANDIDATE_LIBRARY_PATH))

# %%
screen_df = pd.read_csv(CANDIDATE_LIBRARY_PATH).copy()

if "canonical_smiles" not in screen_df.columns:
    raise ValueError("Candidate library must contain 'canonical_smiles'.")

if "molecule_chembl_id" not in screen_df.columns:
    screen_df["molecule_chembl_id"] = [f"BUCHE_HIT_{i}" for i in range(len(screen_df))]

screen_df["canonical_smiles"] = screen_df["canonical_smiles"].apply(canonicalize_smiles)
screen_df = screen_df.dropna(subset=["canonical_smiles"]).copy()
screen_df = screen_df.drop_duplicates(subset=["canonical_smiles"]).reset_index(drop=True)

# build molecular objects and features manually so no label column is required
mols = []
scaffolds = []
morgan_arrays = []
bit_infos = []
maccs_arrays = []
desc_dicts = []

for smi in screen_df["canonical_smiles"]:
    mol = smiles_to_clean_mol(smi)
    mols.append(mol)
    scaffolds.append(get_scaffold_smiles(mol) if mol else None)

    if mol is None:
        morgan_arrays.append(None)
        bit_infos.append(None)
        maccs_arrays.append(None)
        desc_dicts.append(None)
        continue

    mbits, binfo = morgan_bits_with_info(mol, nbits=MORGAN_BITS, radius=MORGAN_RADIUS)
    morgan_arrays.append(mbits)
    bit_infos.append(binfo)

    maccs_arrays.append(maccs_bits(mol) if USE_MACCS else None)
    desc_dicts.append(calc_rdkit_descriptors(mol) if USE_RDKIT_DESCRIPTORS else None)

screen_df["mol"] = mols
screen_df["scaffold"] = scaffolds
screen_df["morgan_bits"] = morgan_arrays
screen_df["bit_info"] = bit_infos
screen_df["maccs_bits"] = maccs_arrays
screen_df["desc_dict"] = desc_dicts

screen_df = screen_df.dropna(subset=["morgan_bits"]).reset_index(drop=True)

feature_blocks = []

X_morgan = np.vstack(screen_df["morgan_bits"].values).astype(np.float32)
feature_blocks.append(X_morgan)

if USE_MACCS:
    X_maccs = np.vstack(screen_df["maccs_bits"].values).astype(np.float32)
    feature_blocks.append(X_maccs)

if USE_RDKIT_DESCRIPTORS:
    desc_df = pd.DataFrame(screen_df["desc_dict"].tolist())
    desc_df.replace([np.inf, -np.inf], np.nan, inplace=True)
    desc_df.fillna(desc_df.median(), inplace=True)
    X_desc = desc_df.values.astype(np.float32)
    feature_blocks.append(X_desc)

X_screen_full = np.hstack(feature_blocks).astype(np.float32)
X_screen_full = np.nan_to_num(X_screen_full, nan=0.0, posinf=0.0, neginf=0.0)

# apply the same selected feature mask from the BuChE ML pipeline
if "feat_mask" not in globals():
    raise ValueError("Feature mask 'feat_mask' not found. Run the BuChE ML pipeline first.")

X_screen_sel = X_screen_full[:, feat_mask]

# use the same scaler from the BuChE ML pipeline
if "scaler" not in globals():
    raise ValueError("Scaler not found. Run the BuChE ML pipeline first.")

X_screen_scaled = scaler.transform(X_screen_sel)

# use the same ensemble from the BuChE ML pipeline
if "ensemble_models" not in globals():
    raise ValueError("Ensemble models not found. Run the BuChE ML pipeline first.")

screen_df["dnn_score"] = ensemble_predict(ensemble_models, X_screen_scaled)

# apply optimized threshold if available
if "opt_thresh" in globals():
    screen_df["predicted_class"] = (screen_df["dnn_score"] >= opt_thresh).astype(int)
else:
    screen_df["predicted_class"] = (screen_df["dnn_score"] >= 0.5).astype(int)

# basic physicochemical properties for docking triage
screen_df["MW"] = screen_df["mol"].apply(lambda m: Descriptors.MolWt(m) if m else np.nan)
screen_df["LogP"] = screen_df["mol"].apply(lambda m: Crippen.MolLogP(m) if m else np.nan)
screen_df["HBD"] = screen_df["mol"].apply(lambda m: Lipinski.NumHDonors(m) if m else np.nan)
screen_df["HBA"] = screen_df["mol"].apply(lambda m: Lipinski.NumHAcceptors(m) if m else np.nan)
screen_df["TPSA"] = screen_df["mol"].apply(lambda m: Descriptors.TPSA(m) if m else np.nan)
screen_df["RotB"] = screen_df["mol"].apply(lambda m: Descriptors.NumRotatableBonds(m) if m else np.nan)

screen_df = screen_df.sort_values("dnn_score", ascending=False).reset_index(drop=True)
screen_df.to_csv("ranked_candidates_full_BuChE.csv", index=False)

print("Screenable compounds:", len(screen_df))
display(screen_df[[
    "molecule_chembl_id", "dnn_score", "predicted_class", "MW", "LogP", "TPSA"
]].head(10))

#%%
filtered_hits = screen_df[
    (screen_df["MW"] <= 600) &
    (screen_df["LogP"] <= 6) &
    (screen_df["HBD"] <= 5) &
    (screen_df["HBA"] <= 10) &
    (screen_df["TPSA"] <= 140) &
    (screen_df["RotB"] <= 12)
].copy()

# optional: keep only predicted actives under the BuChE optimized threshold rule
if "opt_thresh" in globals():
    filtered_hits = filtered_hits[filtered_hits["dnn_score"] >= opt_thresh].copy()

top_hits = filtered_hits.sort_values("dnn_score", ascending=False).head(TOP_N).copy()
top_hits.to_csv(f"top{TOP_N}_hits_for_docking.csv", index=False)

print(f"Top {TOP_N} BuChE hits selected for docking:", len(top_hits))
display(top_hits[[
    "molecule_chembl_id", "dnn_score", "MW", "LogP", "TPSA", "RotB"
]].head(10))

# %%
ensure_clean_folders()
print("Clean BuChE docking workspace ready.")

# re-save important ranking tables
screen_df.to_csv("ranked_candidates_full_BuChE.csv", index=False)
top_hits.to_csv(f"top{TOP_N}_hits_for_docking.csv", index=False)

# %%
from rdkit import Chem
from rdkit.Chem import AllChem

def smiles_to_3d_sdf(smiles, out_sdf, mol_name="BuChE_ligand"):
    mol = Chem.MolFromSmiles(str(smiles))
    if mol is None:
        return False, "invalid smiles"

    # keep largest fragment if helper exists
    if "keep_largest_fragment" in globals():
        mol = keep_largest_fragment(mol)
        if mol is None:
            return False, "no valid fragment"

    try:
        Chem.SanitizeMol(mol)
    except Exception:
        return False, "sanitization failed"

    mol = Chem.AddHs(mol)

    # ETKDG 3D embedding
    try:
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        status = AllChem.EmbedMolecule(mol, params)
        if status != 0:
            return False, "embedding failed"
    except Exception as e:
        return False, f"embedding error: {e}"

    # MMFF optimization
    try:
        if AllChem.MMFFHasAllMoleculeParams(mol):
            AllChem.MMFFOptimizeMolecule(mol)
        else:
            AllChem.UFFOptimizeMolecule(mol)
    except Exception:
        pass

    try:
        mol.SetProp("_Name", str(mol_name))
        writer = Chem.SDWriter(out_sdf)
        writer.write(mol)
        writer.close()
        return True, "success"
    except Exception as e:
        return False, f"sdf write failed: {e}"

# %%
failed_3d = []

for _, row in top_hits.iterrows():
    mol_id = str(row["molecule_chembl_id"])
    smiles = row["canonical_smiles"]
    out_file = os.path.join(SDF_DIR, f"{mol_id}.sdf")

    ok, msg = smiles_to_3d_sdf(smiles, out_file, mol_name=f"BuChE_{mol_id}")
    if not ok:
        failed_3d.append((mol_id, msg))

print("BuChE 3D SDF files created:", len(glob.glob(os.path.join(SDF_DIR, "*.sdf"))))
print("BuChE 3D failures:", len(failed_3d))
if failed_3d:
    print(failed_3d[:10])

