# -*- coding: utf-8 -*-
"""03_Docking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfA5y9Kj94TmKSIzIZwmAExWa3ld-GQs
"""

!pip install -q meeko

!python -m pip install -q py3Dmol

!pip install gemmi

!python -m pip install -q gemmi

!python -m pip install -q prody

!python -m pip install -q meeko gemmi prody

!python -m pip install -q py3Dmol

import os
import py3Dmol

PROTEIN_CLEAN = "4BDS_chainA_clean.pdb"
NATIVE_PDB = "4BDS_native_ligand.pdb"
POSE_DIR = "docked_poses"

def show_docked_pose_buche(ligand_id, width=900, height=650):
    hit_sdf = os.path.join(POSE_DIR, f"{ligand_id}_vina_out.sdf")
    hit_pdbqt = os.path.join(POSE_DIR, f"{ligand_id}_vina_out.pdbqt")

    view = py3Dmol.view(width=width, height=height)

    if not os.path.exists(PROTEIN_CLEAN):
        raise FileNotFoundError(f"BuChE protein file not found: {PROTEIN_CLEAN}")
    if not os.path.exists(NATIVE_PDB):
        raise FileNotFoundError(f"BuChE native ligand file not found: {NATIVE_PDB}")

    with open(PROTEIN_CLEAN, "r") as f:
        view.addModel(f.read(), "pdb")

    with open(NATIVE_PDB, "r") as f:
        view.addModel(f.read(), "pdb")

    if os.path.exists(hit_sdf):
        with open(hit_sdf, "r") as f:
            view.addModel(f.read(), "sdf")
    elif os.path.exists(hit_pdbqt):
        with open(hit_pdbqt, "r") as f:
            view.addModel(f.read(), "pdbqt")
    else:
        raise FileNotFoundError(f"No BuChE docked pose file found for {ligand_id}")

    # model 0 = BuChE protein
    view.setStyle({"model": 0}, {"cartoon": {"color": "lightgray"}})

    # model 1 = native ligand
    view.setStyle({"model": 1}, {"stick": {"colorscheme": "cyanCarbon", "radius": 0.20}})

    # model 2 = docked hit
    view.setStyle({"model": 2}, {"stick": {"colorscheme": "yellowCarbon", "radius": 0.25}})

    # residues near native ligand
    view.addStyle(
        {"model": 0, "within": {"distance": 5, "sel": {"model": 1}}},
        {"stick": {"colorscheme": "greenCarbon", "radius": 0.16}}
    )

    view.zoomTo({"model": 1})
    view.show()
    return view

# %%
import os
import sys
import glob
import site
import shutil
import subprocess

def find_meeko_script(script_name="mk_prepare_ligand.py"):
    p = shutil.which(script_name)
    if p:
        return p

    search_roots = []
    try:
        search_roots.extend(site.getsitepackages())
    except Exception:
        pass

    try:
        search_roots.append(site.getusersitepackages())
    except Exception:
        pass

    search_roots.append(os.path.dirname(sys.executable))
    search_roots.append("/usr/local/bin")
    search_roots.append("/usr/bin")

    seen = set()
    for root in search_roots:
        if not root or root in seen or not os.path.exists(root):
            continue
        seen.add(root)
        hits = glob.glob(os.path.join(root, "**", script_name), recursive=True)
        if hits:
            return hits[0]
    return None

sdf_files = sorted(glob.glob(os.path.join(SDF_DIR, "*.sdf")))
print("BuChE SDF input count:", len(sdf_files))

if len(sdf_files) == 0:
    raise ValueError("No BuChE SDF files found. The 3D ligand generation step must be fixed first.")

mk_path = find_meeko_script("mk_prepare_ligand.py")
print("mk_prepare_ligand.py:", mk_path)

failed_pdbqt = []
success_count = 0

for sdf_file in sdf_files:
    base = os.path.splitext(os.path.basename(sdf_file))[0]
    out_pdbqt = os.path.join(PDBQT_DIR, f"{base}.pdbqt")

    if mk_path is not None:
        cmd = [sys.executable, mk_path, "-i", sdf_file, "-o", out_pdbqt]
    else:
        cmd = [sys.executable, "-m", "meeko.cli.mk_prepare_ligand", "-i", sdf_file, "-o", out_pdbqt]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0 or not os.path.exists(out_pdbqt):
        failed_pdbqt.append({
            "ligand": base,
            "returncode": result.returncode,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        })
    else:
        success_count += 1
        print("BuChE ligand prepared successfully:", base)

print("\nTotal BuChE PDBQT ligands ready:", success_count)

pdbqt_files = sorted(glob.glob(os.path.join(PDBQT_DIR, "*.pdbqt")))
print("Verified BuChE PDBQT files on disk:", len(pdbqt_files))

print("Failures:", len(failed_pdbqt))
if failed_pdbqt:
    for item in failed_pdbqt[:5]:
        print("\n--- FAILED BuChE LIGAND ---")
        print("Ligand:", item["ligand"])
        print("Return code:", item["returncode"])
        print("STDOUT:", item["stdout"])
        print("STDERR:", item["stderr"])

# %%
if not os.path.exists(FULL_PDB):
    get_ipython().system(f"wget -q https://files.rcsb.org/download/{PDB_ID}.pdb -O {FULL_PDB}")

print("Downloaded:", FULL_PDB)

protein_lines = []
ligand_lines = []
cryst1_line = None

NATIVE_RESNAME = "THA"   # 4BDS co-crystal ligand = tacrine

with open(FULL_PDB, "r") as fin:
    for line in fin:
        if line.startswith("CRYST1") and cryst1_line is None:
            cryst1_line = line

        if len(line) < 54:
            continue

        record = line[:6].strip()
        chain_id = line[21].strip()
        resname = line[17:20].strip()

        if record == "ATOM" and chain_id == "A":
            protein_lines.append(line)
        elif record == "HETATM" and chain_id == "A" and resname == NATIVE_RESNAME:
            ligand_lines.append(line)

with open(PROTEIN_CLEAN, "w") as f:
    if cryst1_line:
        f.write(cryst1_line)
    f.writelines(protein_lines)
    f.write("END\n")

with open(NATIVE_PDB, "w") as f:
    if cryst1_line:
        f.write(cryst1_line)
    f.writelines(ligand_lines)
    f.write("END\n")

print("BuChE protein file:", PROTEIN_CLEAN, "atoms:", len(protein_lines))
print("BuChE native ligand file:", NATIVE_PDB, "atoms:", len(ligand_lines))

if len(ligand_lines) == 0:
    raise ValueError(
        f"No native ligand {NATIVE_RESNAME} found in chain A. "
        "Check the BuChE receptor structure and ligand residue name."
    )

# %%
coords = []

with open(NATIVE_PDB, "r") as fin:
    for line in fin:
        if line.startswith("HETATM"):
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
            coords.append([x, y, z])

if len(coords) == 0:
    raise ValueError("No coordinates found in BuChE native ligand PDB.")

coords = np.array(coords)
center = coords.mean(axis=0)
center_x, center_y, center_z = center

print(f"BuChE docking box center: x={center_x:.3f}, y={center_y:.3f}, z={center_z:.3f}")

# %%
mk_receptor_path = shutil.which("mk_prepare_receptor.py")
print("mk_prepare_receptor.py:", mk_receptor_path)

if mk_receptor_path is None:
    raise FileNotFoundError("mk_prepare_receptor.py not found. Install Meeko first.")

cmd = [
    mk_receptor_path,
    "-i", PROTEIN_CLEAN,
    "-o", RECEPTOR_PREFIX,
    "-p",
    "-a",                       # same as --allow_bad_res
    "--default_altloc", "A",
    "--box_enveloping", NATIVE_PDB,
    "--padding", "8.0",
]

result = subprocess.run(cmd, capture_output=True, text=True)

print(result.stdout)
print(result.stderr)
print("Return code:", result.returncode)
print("BuChE receptor exists:", os.path.exists(RECEPTOR_PDBQT))

if not os.path.exists(RECEPTOR_PDBQT):
    raise FileNotFoundError(f"BuChE receptor PDBQT was not created: {RECEPTOR_PDBQT}")

# %%
import os, glob

sdf_files = sorted(glob.glob(os.path.join(SDF_DIR, "*.sdf")))
print("SDF files found:", len(sdf_files))
print(sdf_files[:10])

# %%
import os
import sys
import glob
import site
import shutil
import subprocess

def find_meeko_script(script_name="mk_prepare_ligand.py"):
    p = shutil.which(script_name)
    if p:
        return p

    search_roots = []
    try:
        search_roots.extend(site.getsitepackages())
    except Exception:
        pass

    try:
        search_roots.append(site.getusersitepackages())
    except Exception:
        pass

    search_roots.append(os.path.dirname(sys.executable))
    search_roots.append("/usr/local/bin")
    search_roots.append("/usr/bin")

    seen = set()
    for root in search_roots:
        if not root or root in seen or not os.path.exists(root):
            continue
        seen.add(root)
        hits = glob.glob(os.path.join(root, "**", script_name), recursive=True)
        if hits:
            return hits[0]
    return None

sdf_files = sorted(glob.glob(os.path.join(SDF_DIR, "*.sdf")))
print("BuChE SDF input count:", len(sdf_files))

if len(sdf_files) == 0:
    raise ValueError("No BuChE SDF files found. The 3D ligand generation step must be fixed first.")

mk_path = find_meeko_script("mk_prepare_ligand.py")
print("mk_prepare_ligand.py:", mk_path)

failed_pdbqt = []
success_count = 0

for sdf_file in sdf_files:
    base = os.path.splitext(os.path.basename(sdf_file))[0]
    out_pdbqt = os.path.join(PDBQT_DIR, f"{base}.pdbqt")

    if mk_path is not None:
        cmd = [sys.executable, mk_path, "-i", sdf_file, "-o", out_pdbqt]
    else:
        cmd = [sys.executable, "-m", "meeko.cli.mk_prepare_ligand", "-i", sdf_file, "-o", out_pdbqt]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0 or not os.path.exists(out_pdbqt):
        failed_pdbqt.append({
            "ligand": base,
            "returncode": result.returncode,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        })
    else:
        success_count += 1
        print("BuChE ligand prepared successfully:", base)

print("\nTotal BuChE PDBQT ligands ready:", success_count)

pdbqt_files = sorted(glob.glob(os.path.join(PDBQT_DIR, "*.pdbqt")))
print("Verified BuChE PDBQT files on disk:", len(pdbqt_files))

print("Failures:", len(failed_pdbqt))
if failed_pdbqt:
    for item in failed_pdbqt[:5]:
        print("\n--- FAILED BuChE LIGAND ---")
        print("Ligand:", item["ligand"])
        print("Return code:", item["returncode"])
        print("STDOUT:", item["stdout"])
        print("STDERR:", item["stderr"])

# %%
pdbqt_files = sorted(glob.glob(os.path.join(PDBQT_DIR, "*.pdbqt")))
print("PDBQT files found:", len(pdbqt_files))
print(pdbqt_files[:10])

# %%
from vina import Vina

ligand_files = sorted(glob.glob(os.path.join(PDBQT_DIR, "*.pdbqt")))
results = []

if len(ligand_files) == 0:
    raise ValueError("No ligand PDBQT files found for docking.")

for lig_file in ligand_files:
    lig_name = os.path.splitext(os.path.basename(lig_file))[0]

    try:
        v = Vina(sf_name="vina")
        v.set_receptor(RECEPTOR_PDBQT)
        v.set_ligand_from_file(lig_file)
        v.compute_vina_maps(
            center=[float(center_x), float(center_y), float(center_z)],
            box_size=BOX_SIZE
        )
        v.dock(exhaustiveness=EXHAUSTIVENESS, n_poses=10)

        out_file = os.path.join(POSE_DIR, f"{lig_name}_vina_out.pdbqt")
        v.write_poses(out_file, n_poses=5, overwrite=True)

        energies = v.energies()
        best_score = float(energies[0][0])

        ml_row = top_hits[top_hits["molecule_chembl_id"].astype(str) == lig_name]
        dnn_score = float(ml_row["dnn_score"].iloc[0]) if len(ml_row) else np.nan

        results.append({
            "ligand": lig_name,
            "dnn_score": dnn_score,
            "vina_score_kcal_mol": best_score,
            "pose_file": out_file,
        })

    except Exception as e:
        results.append({
            "ligand": lig_name,
            "dnn_score": np.nan,
            "vina_score_kcal_mol": np.nan,
            "pose_file": "",
            "error": str(e),
        })

dock_df = pd.DataFrame(results)

# sort by docking score ascending (more negative is better)
dock_df = dock_df.sort_values("vina_score_kcal_mol", ascending=True, na_position="last").reset_index(drop=True)
dock_df.to_csv("docking_results.csv", index=False)

display(dock_df.head(10))

# %%
top10 = dock_df.dropna(subset=["vina_score_kcal_mol"]).head(10).copy()
top10.to_csv("top10_docked_hits.csv", index=False)

mk_export_path = shutil.which("mk_export.py")
print("mk_export.py:", mk_export_path)

if mk_export_path is None:
    raise FileNotFoundError("mk_export.py not found. Install Meeko first.")

failed_exports = []

for pose_file in top10["pose_file"]:
    sdf_out = pose_file.replace(".pdbqt", ".sdf")
    resslt = subprocess.run(
        [mk_export_path, pose_file, "-s", sdf_out],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        failed_exports.append((pose_file, result.stderr.strip()))

print("Top 10 exported to SDF.")
print("Export failures:", len(failed_exports))
if failed_exports:
    print(failed_exports[:10])

display(top10)

import os
import pandas as pd
import subprocess

dock_df = pd.read_csv("docking_results.csv").sort_values("vina_score_kcal_mol", ascending=True)
top10 = dock_df.head(10).copy()
top10.to_csv("top10_docked_hits.csv", index=False)

# export SDF for top 10 if missing
for pose_file in top10["pose_file"]:
    sdf_out = pose_file.replace(".pdbqt", ".sdf")
    if not os.path.exists(sdf_out):
        subprocess.run(["mk_export.py", pose_file, "-s", sdf_out], check=True)

print("Top 10 SDF files are ready.")
display(top10)

import os
import pandas as pd

review_file = "pose_review_template.csv"

if os.path.exists(review_file):
    review_df = pd.read_csv(review_file)
    print("Loaded existing review table.")
else:
    review_df = top10.copy()
    review_df["inside_pocket"] = ""
    review_df["sensible_pose"] = ""
    review_df["obvious_clash"] = ""
    review_df["similar_to_native_site"] = ""
    review_df["final_decision"] = ""
    review_df.to_csv(review_file, index=False)
    print("Created new review table.")

display(review_df)

import os
import py3Dmol

PROTEIN_CLEAN = "4BDS_chainA_clean.pdb"
NATIVE_PDB = "4BDS_native_ligand.pdb"
POSE_DIR = "docked_poses"

def show_docked_pose_buche(ligand_id, width=900, height=650):
    hit_sdf = os.path.join(POSE_DIR, f"{ligand_id}_vina_out.sdf")
    hit_pdbqt = os.path.join(POSE_DIR, f"{ligand_id}_vina_out.pdbqt")

    view = py3Dmol.view(width=width, height=height)

    with open(PROTEIN_CLEAN, "r") as f:
        view.addModel(f.read(), "pdb")
    with open(NATIVE_PDB, "r") as f:
        view.addModel(f.read(), "pdb")

    if os.path.exists(hit_sdf):
        with open(hit_sdf, "r") as f:
            view.addModel(f.read(), "sdf")
    elif os.path.exists(hit_pdbqt):
        with open(hit_pdbqt, "r") as f:
            view.addModel(f.read(), "pdbqt")
    else:
        raise FileNotFoundError(f"No BuChE pose file found for {ligand_id}")

    # BuChE protein
    view.setStyle({"model": 0}, {"cartoon": {"color": "lightgray"}})

    # native ligand
    view.setStyle({"model": 1}, {"stick": {"colorscheme": "cyanCarbon", "radius": 0.2}})

    # docked hit
    view.setStyle({"model": 2}, {"stick": {"colorscheme": "yellowCarbon", "radius": 0.25}})

    # highlight pocket residues around native ligand
    view.addStyle(
        {"model": 0, "within": {"distance": 5, "sel": {"model": 1}}},
        {"stick": {"colorscheme": "greenCarbon", "radius": 0.16}}
    )

    view.zoomTo({"model": 1})
    return view

review_df = pd.read_csv("pose_review_template.csv")

# Updated entries for your current top 10 BuChE docked hits

review_df.loc[review_df["ligand"] == "CHEMBL4438120",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "yes", "no", "yes", "keep"]

review_df.loc[review_df["ligand"] == "CHEMBL4459500",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "yes", "no", "yes", "keep"]

review_df.loc[review_df["ligand"] == "CHEMBL4458430",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "yes", "no", "yes", "keep"]

review_df.loc[review_df["ligand"] == "CHEMBL4556575",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "yes", "no", "yes", "keep"]

review_df.loc[review_df["ligand"] == "CHEMBL4559477",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "maybe", "no", "yes", "maybe"]

review_df.loc[review_df["ligand"] == "CHEMBL4540429",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "maybe", "no", "yes", "maybe"]

review_df.loc[review_df["ligand"] == "CHEMBL3642041",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "maybe", "no", "maybe", "maybe"]

review_df.loc[review_df["ligand"] == "CHEMBL2064468",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "maybe", "no", "maybe", "maybe"]

review_df.loc[review_df["ligand"] == "CHEMBL2064469",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["no", "no", "yes", "no", "reject"]

review_df.loc[review_df["ligand"] == "CHEMBL370807",
              ["inside_pocket", "sensible_pose", "obvious_clash", "similar_to_native_site", "final_decision"]] = \
             ["yes", "maybe", "no", "maybe", "maybe"]

review_df.to_csv("pose_review_template.csv", index=False)
display(review_df)

review_df = pd.read_csv("pose_review_template.csv")

needed_cols = [
    "inside_pocket",
    "sensible_pose",
    "obvious_clash",
    "similar_to_native_site",
    "final_decision"
]

incomplete = review_df[review_df[needed_cols].isna().any(axis=1) | (review_df[needed_cols] == "").any(axis=1)]

if len(incomplete) > 0:
    print("These ligands are still incomplete:")
    display(incomplete[["ligand"] + needed_cols])
else:
    print("All top 10 ligands have been reviewed.")

review_df = pd.read_csv("pose_review_template.csv")

final_md_candidates = review_df[
    review_df["final_decision"].isin(["keep", "maybe"])
].copy()

final_md_candidates = final_md_candidates.sort_values("vina_score_kcal_mol", ascending=True)
final_md_candidates.to_csv("final_md_candidates.csv", index=False)

print("Final MD candidates:")
display(final_md_candidates[[
    "ligand",
    "vina_score_kcal_mol",
    "inside_pocket",
    "sensible_pose",
    "obvious_clash",
    "similar_to_native_site",
    "final_decision"
]])

final_md_candidates = pd.read_csv("final_md_candidates.csv")

clear_keeps = final_md_candidates[final_md_candidates["final_decision"] == "keep"].copy()
maybes = final_md_candidates[final_md_candidates["final_decision"] == "maybe"].copy()

# choose 3 keeps first
shortlist = clear_keeps.head(3).copy()

# then add maybe compounds until total reaches 4 or 5
needed = 4 - len(shortlist)
if needed > 0:
    shortlist = pd.concat([shortlist, maybes.head(needed)], ignore_index=True)

# if you want 5 total instead of 4, use this:
# needed = 5 - len(shortlist)

shortlist = shortlist.sort_values("vina_score_kcal_mol", ascending=True)
shortlist.to_csv("final_md_shortlist.csv", index=False)

print("Final shortlist for next stage:")
display(shortlist[[
    "ligand",
    "vina_score_kcal_mol",
    "final_decision"
]])

import os
import shutil
import pandas as pd

PAPER_DIR = "paper_package"
POSE_DIR = "docked_poses"

os.makedirs(PAPER_DIR, exist_ok=True)

files_to_copy = [
    "docking_results.csv",
    "top10_docked_hits.csv",
    "pose_review_template.csv",
    "final_md_candidates.csv",
    "final_md_shortlist.csv",
    "paper_hits_master_table.csv",
    "redocking_summary.csv",
    "shortlist_contact_summary.csv",
    "top30_hits_for_docking.csv",
    "ranked_candidates_full.csv",
    "4EY7_AChE_receptor.pdbqt",
    "4EY7_E20_native.pdb",
    "4EY7_E20_redocked_out.pdbqt",
    "4EY7_E20_redocked_out.sdf",
]

for f in files_to_copy:
    if os.path.exists(f):
        shutil.copy(f, os.path.join(PAPER_DIR, os.path.basename(f)))

shortlist = pd.read_csv("final_md_shortlist.csv")
for lig in shortlist["ligand"]:
    for ext in ["pdbqt", "sdf"]:
        f = os.path.join(POSE_DIR, f"{lig}_vina_out.{ext}")
        if os.path.exists(f):
            shutil.copy(f, os.path.join(PAPER_DIR, os.path.basename(f)))

print("Updated paper package saved in:", PAPER_DIR)
print(sorted(os.listdir(PAPER_DIR)))

import os
import pandas as pd
import subprocess

DOCK_FILE = "docking_results.csv"
TOP_N_REVIEW = 20

if not os.path.exists(DOCK_FILE):
    raise FileNotFoundError(f"{DOCK_FILE} not found")

dock_df = pd.read_csv(DOCK_FILE)

required_cols = ["ligand", "vina_score_kcal_mol", "pose_file"]
missing = [c for c in required_cols if c not in dock_df.columns]
if missing:
    raise ValueError(f"Missing required columns: {missing}")

dock_df = dock_df.dropna(subset=["ligand", "vina_score_kcal_mol", "pose_file"]).copy()
dock_df = dock_df.sort_values("vina_score_kcal_mol", ascending=True).drop_duplicates(subset=["ligand"])

top_review = dock_df.head(TOP_N_REVIEW).copy()
top_review.to_csv("top_review_hits.csv", index=False)

export_log = []
for pose_file in top_review["pose_file"]:
    sdf_out = pose_file.replace(".pdbqt", ".sdf")
    try:
        if not os.path.exists(pose_file):
            raise FileNotFoundError(f"Pose file missing: {pose_file}")
        if not os.path.exists(sdf_out):
            subprocess.run(["mk_export.py", pose_file, "-s", sdf_out], check=True)
        export_log.append({"pose_file": pose_file, "sdf_file": sdf_out, "status": "success"})
    except Exception as e:
        export_log.append({"pose_file": pose_file, "sdf_file": sdf_out, "status": f"failed: {e}"})

export_log_df = pd.DataFrame(export_log)
export_log_df.to_csv("sdf_export_log.csv", index=False)

print(f"Top {TOP_N_REVIEW} review hits prepared.")
display(top_review.head(10))
display(export_log_df)

import os
import pandas as pd
from datetime import datetime

review_file = "pose_review_template.csv"

review_columns = [
    "ligand",
    "vina_score_kcal_mol",
    "pose_file",
    "distance_to_native_centroid",
    "num_contacts_4A",
    "key_residue_contact",
    "inside_pocket",
    "sensible_pose",
    "obvious_clash",
    "similar_to_native_site",
    "final_decision",
    "reviewer",
    "review_date",
    "notes"
]

if os.path.exists(review_file):
    review_df = pd.read_csv(review_file)
    print("Loaded existing review table.")
else:
    review_df = top_review.copy()
    for col in review_columns:
        if col not in review_df.columns:
            review_df[col] = ""
    review_df = review_df[review_columns]
    review_df.to_csv(review_file, index=False)
    print("Created new review table.")

display(review_df.head(10))

import os
import py3Dmol

PROTEIN_CLEAN = "4BDS_chainA_clean.pdb"
NATIVE_PDB = "4BDS_native_ligand.pdb"
POSE_DIR = "docked_poses"

# BuChE catalytic gorge / binding-site residues for 4BDS-style inspection
KEY_RESIDUES = [82, 197, 286, 328, 332, 440, 117, 199, 434]

def show_docked_pose_buche(ligand_id, width=950, height=700):
    hit_sdf = os.path.join(POSE_DIR, f"{ligand_id}_vina_out.sdf")
    hit_pdbqt = os.path.join(POSE_DIR, f"{ligand_id}_vina_out.pdbqt")

    view = py3Dmol.view(width=width, height=height)

    with open(PROTEIN_CLEAN, "r") as f:
        view.addModel(f.read(), "pdb")
    with open(NATIVE_PDB, "r") as f:
        view.addModel(f.read(), "pdb")

    if os.path.exists(hit_sdf):
        with open(hit_sdf, "r") as f:
            view.addModel(f.read(), "sdf")
    elif os.path.exists(hit_pdbqt):
        with open(hit_pdbqt, "r") as f:
            view.addModel(f.read(), "pdbqt")
    else:
        raise FileNotFoundError(f"No BuChE pose file found for {ligand_id}")

    # model 0 = BuChE protein
    view.setStyle({"model": 0}, {"cartoon": {"color": "lightgray"}})

    # model 1 = native ligand
    view.setStyle({"model": 1}, {"stick": {"colorscheme": "cyanCarbon", "radius": 0.20}})

    # model 2 = docked ligand
    view.setStyle({"model": 2}, {"stick": {"colorscheme": "yellowCarbon", "radius": 0.25}})

    # highlight residues near native ligand
    view.addStyle(
        {"model": 0, "within": {"distance": 5, "sel": {"model": 1}}},
        {"stick": {"colorscheme": "greenCarbon", "radius": 0.16}}
    )

    # highlight key BuChE binding-site residues
    for resi in KEY_RESIDUES:
        view.addStyle(
            {"model": 0, "resi": str(resi)},
            {"stick": {"colorscheme": "magentaCarbon", "radius": 0.18}}
        )

    view.zoomTo({"model": 1})
    return view

import pandas as pd

review_df = pd.read_csv("pose_review_template.csv")

required_cols = [
    "ligand",
    "vina_score_kcal_mol",
    "pose_file",
    "inside_pocket",
    "sensible_pose",
    "obvious_clash",
    "similar_to_native_site",
    "final_decision",
    "pose_quality_score",
    "distance_to_native_centroid",
    "num_contacts_4A",
    "key_residue_contact",
    "reviewer",
    "review_date",
    "notes"
]

for col in required_cols:
    if col not in review_df.columns:
        review_df[col] = ""

review_df = review_df[required_cols]
review_df.to_csv("pose_review_template.csv", index=False)

print("Updated pose_review_template.csv columns:")
print(review_df.columns.tolist())
display(review_df.head())

import pandas as pd
from datetime import datetime

review_df = pd.read_csv("pose_review_template.csv")

mapping = {"yes": 1.0, "maybe": 0.5, "no": 0.0}
clash_mapping = {"no": 1.0, "maybe": 0.5, "yes": 0.0}

review_df["inside_pocket_score"] = review_df["inside_pocket"].astype(str).str.lower().map(mapping)
review_df["sensible_pose_score"] = review_df["sensible_pose"].astype(str).str.lower().map(mapping)
review_df["similar_to_native_site_score"] = review_df["similar_to_native_site"].astype(str).str.lower().map(mapping)
review_df["clash_score"] = review_df["obvious_clash"].astype(str).str.lower().map(clash_mapping)

review_df["pose_quality_score"] = (
    review_df["inside_pocket_score"].fillna(0) +
    review_df["sensible_pose_score"].fillna(0) +
    review_df["similar_to_native_site_score"].fillna(0) +
    review_df["clash_score"].fillna(0)
)

if "reviewer" in review_df.columns:
    review_df["reviewer"] = review_df["reviewer"].replace("", "BILAL")

if "review_date" in review_df.columns:
    review_df["review_date"] = datetime.today().strftime("%Y-%m-%d")

review_df.to_csv("pose_review_template.csv", index=False)

display(review_df[[
    "ligand",
    "vina_score_kcal_mol",
    "inside_pocket",
    "sensible_pose",
    "obvious_clash",
    "similar_to_native_site",
    "pose_quality_score",
    "final_decision"
]])

import pandas as pd

review_df = pd.read_csv("pose_review_template.csv")

three_state_cols = [
    "inside_pocket",
    "sensible_pose",
    "obvious_clash",
    "similar_to_native_site"
]
allowed_three = {"yes", "no", "maybe"}
allowed_final = {"keep", "maybe", "reject"}

for col in three_state_cols:
    review_df[col] = review_df[col].astype(str).str.lower().str.strip()

review_df["final_decision"] = review_df["final_decision"].astype(str).str.lower().str.strip()

bad_entries = {}

for col in three_state_cols:
    bad = review_df[~review_df[col].isin(allowed_three)]
    if len(bad) > 0:
        bad_entries[col] = bad[["ligand", col]]

bad_final = review_df[~review_df["final_decision"].isin(allowed_final)]

if bad_entries:
    print("Unexpected values found:")
    for col, bad_df in bad_entries.items():
        print(f"\nColumn: {col}")
        display(bad_df)

if len(bad_final) > 0:
    print("\nUnexpected values in final_decision:")
    display(bad_final[["ligand", "final_decision"]])

needed_cols = three_state_cols + ["final_decision"]
incomplete = review_df[
    review_df[needed_cols].isna().any(axis=1) |
    (review_df[needed_cols] == "").any(axis=1)
]

if len(incomplete) > 0:
    print("These ligands are still incomplete:")
    display(incomplete[["ligand"] + needed_cols])
else:
    print("All reviewed ligands have valid entries.")

import pandas as pd

review_df = pd.read_csv("pose_review_template.csv")

final_md_candidates = review_df[
    review_df["final_decision"].isin(["keep", "maybe"])
].copy()

final_md_candidates["vina_score_kcal_mol"] = pd.to_numeric(
    final_md_candidates["vina_score_kcal_mol"], errors="coerce"
)
final_md_candidates["pose_quality_score"] = pd.to_numeric(
    final_md_candidates["pose_quality_score"], errors="coerce"
).fillna(0)

# convert docking score so higher ranking value means better docking
final_md_candidates["docking_rank_score"] = -final_md_candidates["vina_score_kcal_mol"]

# combined score: adjust weights later if needed
final_md_candidates["combined_selection_score"] = (
    0.6 * final_md_candidates["docking_rank_score"] +
    0.4 * final_md_candidates["pose_quality_score"]
)

final_md_candidates = final_md_candidates.sort_values(
    ["combined_selection_score", "vina_score_kcal_mol"],
    ascending=[False, True]
)

final_md_candidates.to_csv("final_md_candidates.csv", index=False)

print("Final MD candidates:")
display(final_md_candidates[[
    "ligand",
    "vina_score_kcal_mol",
    "pose_quality_score",
    "combined_selection_score",
    "final_decision"
]])

import pandas as pd

final_md_candidates = pd.read_csv("final_md_candidates.csv")

final_md_candidates["vina_score_kcal_mol"] = pd.to_numeric(
    final_md_candidates["vina_score_kcal_mol"], errors="coerce"
)
final_md_candidates["pose_quality_score"] = pd.to_numeric(
    final_md_candidates["pose_quality_score"], errors="coerce"
)
final_md_candidates["combined_selection_score"] = pd.to_numeric(
    final_md_candidates["combined_selection_score"], errors="coerce"
)

clear_keeps = final_md_candidates[
    (final_md_candidates["final_decision"] == "keep") &
    (final_md_candidates["pose_quality_score"] >= 3.0)
].copy()

maybes = final_md_candidates[
    (final_md_candidates["final_decision"] == "maybe") &
    (final_md_candidates["pose_quality_score"] >= 2.5)
].copy()

MAX_SHORTLIST = 5

shortlist = clear_keeps.copy()
remaining = MAX_SHORTLIST - len(shortlist)

if remaining > 0:
    shortlist = pd.concat([shortlist, maybes.head(remaining)], ignore_index=True)

shortlist = shortlist.sort_values(
    ["combined_selection_score", "vina_score_kcal_mol"],
    ascending=[False, True]
)

shortlist.to_csv("final_md_shortlist.csv", index=False)

print("Final shortlist for next stage:")
display(shortlist[[
    "ligand",
    "vina_score_kcal_mol",
    "pose_quality_score",
    "combined_selection_score",
    "final_decision"
]])

import os
import shutil
import pandas as pd
import platform
import sys

PAPER_DIR = "paper_package"
POSE_DIR = "docked_poses"

os.makedirs(PAPER_DIR, exist_ok=True)

files_to_copy = [
    "docking_results.csv",
    "top10_docked_hits.csv",
    "pose_review_template.csv",
    "final_md_candidates.csv",
    "final_md_shortlist.csv",
    "paper_hits_master_table.csv",
    "top30_hits_for_docking.csv",
    "ranked_candidates_full_BuChE.csv",
    "4BDS_BuChE_receptor.pdbqt",
    "4BDS_native_ligand.pdb",
    "4BDS_native_redocked_out.pdbqt",
    "4BDS_native_redocked_out.sdf",
    "redocking_summary.csv",
    "shortlist_contact_summary.csv",
    "sdf_export_log.csv"
]

copied_files = []
missing_files = []

for f in files_to_copy:
    if os.path.exists(f):
        shutil.copy(f, os.path.join(PAPER_DIR, os.path.basename(f)))
        copied_files.append(f)
    else:
        missing_files.append(f)

if os.path.exists("final_md_shortlist.csv"):
    shortlist = pd.read_csv("final_md_shortlist.csv")
    for lig in shortlist["ligand"]:
        for ext in ["pdbqt", "sdf"]:
            f = os.path.join(POSE_DIR, f"{lig}_vina_out.{ext}")
            if os.path.exists(f):
                shutil.copy(f, os.path.join(PAPER_DIR, os.path.basename(f)))

meta = pd.DataFrame([{
    "python_version": sys.version,
    "platform": platform.platform()
}])
meta.to_csv(os.path.join(PAPER_DIR, "environment_metadata.csv"), index=False)

print("Updated BuChE paper package saved in:", PAPER_DIR)
print("\nCopied files:")
print(sorted(os.listdir(PAPER_DIR)))

if missing_files:
    print("\nFiles not found yet:")
    for f in missing_files:
        print("-", f)

import pandas as pd

shortlist = pd.read_csv("final_md_shortlist.csv")

summary_cols = [
    "ligand",
    "vina_score_kcal_mol",
    "pose_quality_score",
    "combined_selection_score",
    "final_decision"
]

summary_cols = [c for c in summary_cols if c in shortlist.columns]

shortlist_summary = shortlist[summary_cols].copy()
shortlist_summary = shortlist_summary.sort_values("vina_score_kcal_mol", ascending=True)
shortlist_summary.to_csv("shortlist_summary_table.csv", index=False)

print("Shortlist summary:")
display(shortlist_summary)

import pandas as pd
import matplotlib.pyplot as plt

dock_df = pd.read_csv("docking_results.csv")
shortlist = pd.read_csv("final_md_shortlist.csv")

plt.figure(figsize=(8,5))
plt.hist(dock_df["vina_score_kcal_mol"], bins=30, edgecolor="black")
plt.xlabel("Vina docking score (kcal/mol)")
plt.ylabel("Number of compounds")
plt.title("Distribution of docking scores for screened compounds")

for score in shortlist["vina_score_kcal_mol"]:
    plt.axvline(score, linestyle="--")

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

dock_df = pd.read_csv("docking_results.csv").sort_values("vina_score_kcal_mol", ascending=True)
top10 = dock_df.head(10)

plt.figure(figsize=(10,5))
plt.bar(top10["ligand"], top10["vina_score_kcal_mol"])
plt.xticks(rotation=60, ha="right")
plt.ylabel("Vina docking score (kcal/mol)")
plt.xlabel("Ligand")
plt.title("Top 10 docked compounds")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

review_df = pd.read_csv("pose_review_template.csv")
counts = review_df["final_decision"].value_counts()

plt.figure(figsize=(6,4))
plt.bar(counts.index, counts.values)
plt.xlabel("Final decision")
plt.ylabel("Number of compounds")
plt.title("Manual pose review outcome")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

review_df = pd.read_csv("pose_review_template.csv")

plt.figure(figsize=(7,5))
plt.scatter(review_df["pose_quality_score"], review_df["vina_score_kcal_mol"])
plt.xlabel("Pose quality score")
plt.ylabel("Vina docking score (kcal/mol)")
plt.title("Pose quality vs docking score")

for _, row in review_df.iterrows():
    plt.text(row["pose_quality_score"], row["vina_score_kcal_mol"], row["ligand"], fontsize=8)

plt.tight_layout()
plt.show()