# -*- coding: utf-8 -*-
"""05_Redocking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IAUAx6L6XwkDQAcUvxgrvgk2igjqd5QY
"""

!apt-get update -qq
!apt-get install -y openbabel

!which obabel
!obabel -V

!apt-get update -qq
!apt-get install -y autodock-vina

import os
import subprocess
import shutil

native_pdb = "4BDS_native_ligand.pdb"
native_sdf = "4BDS_native_ligand.sdf"
native_h_sdf = "4BDS_native_ligand_H.sdf"
native_pdbqt = "4BDS_native_ligand.pdbqt"

if not os.path.exists(native_pdb):
    raise FileNotFoundError(f"{native_pdb} not found")

obabel_path = shutil.which("obabel")
if obabel_path is None:
    raise FileNotFoundError(
        "Open Babel is not installed. Install it first using: !apt-get install -y openbabel"
    )

prep_path = shutil.which("mk_prepare_ligand.py")
if prep_path is None:
    raise FileNotFoundError(
        "mk_prepare_ligand.py not found. Install Meeko first using: !pip install -q meeko"
    )

# Step 1: Convert PDB -> SDF
print("Converting PDB to SDF...")
conv1 = subprocess.run(
    [obabel_path, native_pdb, "-O", native_sdf],
    capture_output=True,
    text=True
)
print("PDB -> SDF return code:", conv1.returncode)
print("STDOUT:\n", conv1.stdout)
print("STDERR:\n", conv1.stderr)

if conv1.returncode != 0 or not os.path.exists(native_sdf):
    raise RuntimeError("Failed to convert native ligand PDB to SDF")

# Step 2: Add explicit hydrogens
print("Adding explicit hydrogens...")
conv2 = subprocess.run(
    [obabel_path, native_sdf, "-O", native_h_sdf, "-h"],
    capture_output=True,
    text=True
)
print("Add H return code:", conv2.returncode)
print("STDOUT:\n", conv2.stdout)
print("STDERR:\n", conv2.stderr)

if conv2.returncode != 0 or not os.path.exists(native_h_sdf):
    raise RuntimeError("Failed to generate hydrogen-added SDF")

# Step 3: Prepare ligand PDBQT from hydrogen-added SDF
print("Preparing ligand PDBQT...")
prep = subprocess.run(
    [prep_path, "-i", native_h_sdf, "-o", native_pdbqt],
    capture_output=True,
    text=True
)
print("Prepare return code:", prep.returncode)
print("STDOUT:\n", prep.stdout)
print("STDERR:\n", prep.stderr)

if prep.returncode != 0:
    raise RuntimeError("Ligand preparation failed")

if not os.path.exists(native_pdbqt):
    raise FileNotFoundError(f"{native_pdbqt} was not created")

print(f"Successfully created: {native_pdbqt}")

import subprocess
import os

native_sdf = "4BDS_native_ligand.sdf"
native_pdbqt = "4BDS_native_ligand.pdbqt"

if not os.path.exists(native_sdf):
    raise FileNotFoundError(f"{native_sdf} not found")

result = subprocess.run(
    ["mk_prepare_ligand.py", "-i", native_sdf, "-o", native_pdbqt],
    capture_output=True,
    text=True
)

print("Return code:", result.returncode)
print("STDOUT:\n", result.stdout)
print("STDERR:\n", result.stderr)

from rdkit import Chem
from rdkit.Chem import AllChem
import os

native_pdb = "4BDS_native_ligand.pdb"
native_sdf = "4BDS_native_ligand_explicitH.sdf"

if not os.path.exists(native_pdb):
    raise FileNotFoundError(f"{native_pdb} not found")

mol = Chem.MolFromPDBFile(native_pdb, removeHs=False, sanitize=False)
if mol is None:
    raise ValueError("RDKit could not read the BuChE native ligand PDB")

# sanitize first
Chem.SanitizeMol(mol)

# force explicit hydrogens
mol = Chem.AddHs(mol, addCoords=True)

# if no conformer is present, generate one
if mol.GetNumConformers() == 0:
    AllChem.EmbedMolecule(mol, randomSeed=42)
    AllChem.UFFOptimizeMolecule(mol)

writer = Chem.SDWriter(native_sdf)
writer.SetKekulize(False)
writer.write(mol)
writer.close()

print("Saved:", native_sdf)
print("Num atoms:", mol.GetNumAtoms())
print("Num H atoms included explicitly for BuChE native ligand.")

from rdkit import Chem

mol_check = Chem.SDMolSupplier("4BDS_native_ligand_explicitH.sdf", removeHs=False)[0]

if mol_check is None:
    raise ValueError("Could not read written BuChE native ligand SDF")

num_atoms = mol_check.GetNumAtoms()
num_H = sum(1 for atom in mol_check.GetAtoms() if atom.GetAtomicNum() == 1)

print("Total atoms:", num_atoms)
print("Explicit H atoms:", num_H)

from rdkit import Chem
from rdkit.Chem import AllChem

mol = Chem.MolFromPDBFile("4BDS_native_ligand.pdb", removeHs=True, sanitize=False)
if mol is None:
    raise ValueError("Could not read BuChE native ligand PDB")

Chem.SanitizeMol(mol)
mol = Chem.RemoveHs(mol)
mol = Chem.AddHs(mol, addCoords=True)

if mol.GetNumConformers() == 0:
    AllChem.EmbedMolecule(mol, randomSeed=42)
    AllChem.UFFOptimizeMolecule(mol)

writer = Chem.SDWriter("4BDS_native_ligand_explicitH.sdf")
writer.SetKekulize(False)
writer.write(mol)
writer.close()

print("Rewrote BuChE native ligand with explicit Hs.")

from vina import Vina
import os

receptor_pdbqt = "4BDS_BuChE_receptor.pdbqt"
native_pdbqt = "4BDS_native_ligand.pdbqt"
redock_out = "4BDS_native_redocked_out.pdbqt"

v = Vina(sf_name="vina")
v.set_receptor(receptor_pdbqt)
v.set_ligand_from_file(native_pdbqt)

v.compute_vina_maps(
    center=[float(center_x), float(center_y), float(center_z)],
    box_size=BOX_SIZE
)

v.dock(exhaustiveness=16, n_poses=10)
v.write_poses(redock_out, n_poses=5, overwrite=True)

energies = v.energies()
print("Best redocking score:", energies[0][0])
print("Saved:", redock_out)

import shutil
import os

print("vina on PATH:", shutil.which("vina"))
print("vina_1.2.5 on PATH:", shutil.which("vina_1.2.5"))
print("vina_1.2.3 on PATH:", shutil.which("vina_1.2.3"))

import shutil
print("vina on PATH:", shutil.which("vina"))

import os
import shutil
import subprocess

vina_exe = shutil.which("vina")
if vina_exe is None:
    raise FileNotFoundError("Vina executable not found. Install autodock-vina first.")

receptor = "4BDS_BuChE_receptor.pdbqt"
ligand = "4BDS_native_ligand.pdbqt"
out_pdbqt = "4BDS_native_redocked_out.pdbqt"
log_file = "4BDS_native_redocking_log.txt"

if not os.path.exists(receptor):
    raise FileNotFoundError(f"{receptor} not found")
if not os.path.exists(ligand):
    raise FileNotFoundError(f"{ligand} not found")

cmd = [
    vina_exe,
    "--receptor", receptor,
    "--ligand", ligand,
    "--center_x", f"{center_x:.3f}",
    "--center_y", f"{center_y:.3f}",
    "--center_z", f"{center_z:.3f}",
    "--size_x", "20",
    "--size_y", "20",
    "--size_z", "20",
    "--out", out_pdbqt,
    "--log", log_file
]

result = subprocess.run(cmd, capture_output=True, text=True)

print("Return code:", result.returncode)
print("STDOUT:\n", result.stdout)
print("STDERR:\n", result.stderr)

if result.returncode == 0:
    print("Saved:", out_pdbqt)
    print("Saved:", log_file)

import os
import shutil
import subprocess

vina_exe = shutil.which("vina")
if vina_exe is None:
    raise FileNotFoundError("Vina executable not found. Install autodock-vina first.")

receptor = "4BDS_BuChE_receptor.pdbqt"
ligand = "4BDS_native_ligand.pdbqt"
out_pdbqt = "4BDS_native_redocked_out.pdbqt"

if not os.path.exists(receptor):
    raise FileNotFoundError(f"{receptor} not found")
if not os.path.exists(ligand):
    raise FileNotFoundError(f"{ligand} not found")

cmd = [
    vina_exe,
    "--receptor", receptor,
    "--ligand", ligand,
    "--center_x", f"{center_x:.3f}",
    "--center_y", f"{center_y:.3f}",
    "--center_z", f"{center_z:.3f}",
    "--size_x", "20",
    "--size_y", "20",
    "--size_z", "20",
    "--out", out_pdbqt,
    "--exhaustiveness", "8",
    "--num_modes", "9"
]

result = subprocess.run(cmd, capture_output=True, text=True)

print("Return code:", result.returncode)
print("STDOUT:\n", result.stdout)
print("STDERR:\n", result.stderr)

if result.returncode == 0:
    print("Saved:", out_pdbqt)

import os
import subprocess

redocked_pdbqt = "4BDS_native_redocked_out.pdbqt"
redocked_sdf = "4BDS_native_redocked_out.sdf"

if not os.path.exists(redocked_pdbqt):
    raise FileNotFoundError(f"{redocked_pdbqt} not found")

result = subprocess.run(
    ["mk_export.py", redocked_pdbqt, "-s", redocked_sdf],
    capture_output=True,
    text=True
)

print("Return code:", result.returncode)
print("STDOUT:\n", result.stdout)
print("STDERR:\n", result.stderr)

if result.returncode == 0:
    print("Saved:", redocked_sdf)

import os
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdMolAlign

native_sdf = "4BDS_native_ligand_explicitH.sdf"
redocked_sdf = "4BDS_native_redocked_out.sdf"

if not os.path.exists(native_sdf):
    raise FileNotFoundError(f"{native_sdf} not found")
if not os.path.exists(redocked_sdf):
    raise FileNotFoundError(f"{redocked_sdf} not found")

native_mol = Chem.SDMolSupplier(native_sdf, removeHs=False)[0]
redocked_mol = Chem.SDMolSupplier(redocked_sdf, removeHs=False)[0]

if native_mol is None:
    raise ValueError("Could not read BuChE native ligand SDF")
if redocked_mol is None:
    raise ValueError("Could not read BuChE redocked ligand SDF")

rmsd = rdMolAlign.GetBestRMS(redocked_mol, native_mol)

summary_df = pd.DataFrame([{
    "ligand": "THA",
    "rmsd_angstrom": rmsd
}])

summary_df.to_csv("redocking_summary.csv", index=False)
print(summary_df)

import pandas as pd
import matplotlib.pyplot as plt

redock = pd.read_csv("redocking_summary.csv")

plt.figure(figsize=(5, 4))
plt.bar(["THA redocking"], redock["rmsd_angstrom"].values)
plt.ylabel("RMSD (Å)")
plt.title("BuChE docking protocol validation")
plt.axhline(2.0, linestyle="--")
plt.tight_layout()
plt.show()

import os
import py3Dmol

PROTEIN_CLEAN = "4BDS_chainA_clean.pdb"
NATIVE_PDB = "4BDS_native_ligand.pdb"
REDOCKED_SDF = "4BDS_native_redocked_out.sdf"

view = py3Dmol.view(width=900, height=650)

with open(PROTEIN_CLEAN, "r") as f:
    view.addModel(f.read(), "pdb")

with open(NATIVE_PDB, "r") as f:
    view.addModel(f.read(), "pdb")

with open(REDOCKED_SDF, "r") as f:
    view.addModel(f.read(), "sdf")

view.setStyle({"model": 0}, {"cartoon": {"color": "lightgray"}})
view.setStyle({"model": 1}, {"stick": {"colorscheme": "cyanCarbon", "radius": 0.22}})
view.setStyle({"model": 2}, {"stick": {"colorscheme": "yellowCarbon", "radius": 0.18}})

view.addStyle(
    {"model": 0, "within": {"distance": 5, "sel": {"model": 1}}},
    {"stick": {"colorscheme": "greenCarbon", "radius": 0.16}}
)

view.zoomTo({"model": 1})
view.show()

import os
import numpy as np
import pandas as pd
from rdkit import Chem

PROTEIN_PDB = "4BDS_chainA_clean.pdb"
NATIVE_PDB = "4BDS_native_ligand.pdb"
POSE_DIR = "docked_poses"

def parse_protein_atoms(pdb_file):
    atoms = []
    with open(pdb_file, "r") as f:
        for line in f:
            if line.startswith(("ATOM", "HETATM")):
                atom_name = line[12:16].strip()
                res_name = line[17:20].strip()
                chain_id = line[21].strip()
                res_id = line[22:26].strip()
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                element = line[76:78].strip() if len(line) >= 78 else atom_name[0]
                atoms.append({
                    "atom_name": atom_name,
                    "res_name": res_name,
                    "chain_id": chain_id,
                    "res_id": res_id,
                    "x": x,
                    "y": y,
                    "z": z,
                    "element": element
                })
    return pd.DataFrame(atoms)

def load_ligand_coords_from_sdf(sdf_file):
    mol = Chem.SDMolSupplier(sdf_file, removeHs=False)[0]
    if mol is None:
        raise ValueError(f"Could not read SDF: {sdf_file}")
    conf = mol.GetConformer()
    coords = []
    for i, atom in enumerate(mol.GetAtoms()):
        pos = conf.GetAtomPosition(i)
        coords.append({
            "atom_idx": i,
            "element": atom.GetSymbol(),
            "x": pos.x,
            "y": pos.y,
            "z": pos.z
        })
    return pd.DataFrame(coords)

def load_ligand_coords_from_pdb(pdb_file):
    coords = []
    with open(pdb_file, "r") as f:
        for line in f:
            if line.startswith(("ATOM", "HETATM")):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                atom_name = line[12:16].strip()
                element = line[76:78].strip() if len(line) >= 78 else atom_name[0]
                coords.append({
                    "atom_idx": len(coords),
                    "element": element,
                    "x": x,
                    "y": y,
                    "z": z
                })
    return pd.DataFrame(coords)

protein_atoms = parse_protein_atoms(PROTEIN_PDB)
print("BuChE protein atoms loaded:", len(protein_atoms))
protein_atoms.head()

import numpy as np
import pandas as pd

def compute_contacts(protein_df, ligand_df, cutoff=4.0):
    contacts = []
    lig_xyz = ligand_df[["x", "y", "z"]].values
    prot_xyz = protein_df[["x", "y", "z"]].values

    for i, p in protein_df.iterrows():
        dists = np.sqrt(((lig_xyz - prot_xyz[i]) ** 2).sum(axis=1))
        min_dist = dists.min()
        if min_dist <= cutoff:
            contacts.append({
                "residue": f"{p['res_name']}{p['res_id']}",
                "chain": p["chain_id"],
                "atom_name": p["atom_name"],
                "min_distance": min_dist
            })
    contact_df = pd.DataFrame(contacts)
    if len(contact_df) == 0:
        return contact_df
    contact_df = contact_df.sort_values("min_distance")
    return contact_df

native_lig = load_ligand_coords_from_pdb(NATIVE_PDB)
native_contacts = compute_contacts(protein_atoms, native_lig, cutoff=4.0)

native_contacts.to_csv("BuChE_native_contact_atoms.csv", index=False)
display(native_contacts.head(20))

native_residue_contacts = (
    native_contacts.groupby(["residue", "chain"], as_index=False)["min_distance"]
    .min()
    .sort_values("min_distance")
)

native_residue_contacts.to_csv("native_contact_residues.csv", index=False)
print("Native contacting residues:")
display(native_residue_contacts.head(20))

shortlist = pd.read_csv("final_md_shortlist.csv")

all_contact_rows = []
residue_summary_rows = []

for lig in shortlist["ligand"]:
    sdf_file = os.path.join(POSE_DIR, f"{lig}_vina_out.sdf")
    if not os.path.exists(sdf_file):
        print(f"Missing SDF for {lig}: {sdf_file}")
        continue

    lig_df = load_ligand_coords_from_sdf(sdf_file)
    lig_contacts = compute_contacts(protein_atoms, lig_df, cutoff=4.0)

    if len(lig_contacts) == 0:
        continue

    lig_contacts["ligand"] = lig
    all_contact_rows.append(lig_contacts)

    residue_level = (
        lig_contacts.groupby(["ligand", "residue", "chain"], as_index=False)["min_distance"]
        .min()
        .sort_values(["ligand", "min_distance"])
    )
    residue_summary_rows.append(residue_level)

if all_contact_rows:
    all_contact_df = pd.concat(all_contact_rows, ignore_index=True)
    all_contact_df.to_csv("shortlist_contact_atoms.csv", index=False)
    print("Saved shortlist_contact_atoms.csv")
else:
    all_contact_df = pd.DataFrame()

if residue_summary_rows:
    shortlist_contact_summary = pd.concat(residue_summary_rows, ignore_index=True)
    shortlist_contact_summary.to_csv("shortlist_contact_summary.csv", index=False)
    print("Saved shortlist_contact_summary.csv")
    display(shortlist_contact_summary.head(30))
else:
    shortlist_contact_summary = pd.DataFrame()
    print("No ligand contacts found.")

native_residues = set(native_residue_contacts["residue"].tolist())

comparison_rows = []

for lig in shortlist["ligand"]:
    lig_res = shortlist_contact_summary[shortlist_contact_summary["ligand"] == lig]
    lig_residues = set(lig_res["residue"].tolist())

    shared = lig_residues.intersection(native_residues)
    unique_lig = lig_residues - native_residues
    unique_native = native_residues - lig_residues

    comparison_rows.append({
        "ligand": lig,
        "n_ligand_contact_residues": len(lig_residues),
        "n_native_contact_residues": len(native_residues),
        "n_shared_with_native": len(shared),
        "shared_residues": ", ".join(sorted(shared)),
        "unique_ligand_residues": ", ".join(sorted(unique_lig)),
        "native_only_residues": ", ".join(sorted(unique_native))
    })

interaction_comparison_df = pd.DataFrame(comparison_rows)
interaction_comparison_df.to_csv("interaction_comparison_vs_native.csv", index=False)

display(interaction_comparison_df)

KEY_RESIDUES = {
    "Ser203", "His447", "Glu334",
    "Trp86", "Tyr337", "Phe338", "Tyr124"
}

key_rows = []

for lig in shortlist["ligand"]:
    lig_residues = set(
        shortlist_contact_summary.loc[
            shortlist_contact_summary["ligand"] == lig, "residue"
        ].tolist()
    )

    matched = lig_residues.intersection(KEY_RESIDUES)

    key_rows.append({
        "ligand": lig,
        "n_key_residues_contacted": len(matched),
        "key_residues_contacted": ", ".join(sorted(matched))
    })

key_contact_df = pd.DataFrame(key_rows)
key_contact_df.to_csv("key_residue_contacts.csv", index=False)
display(key_contact_df)

import matplotlib.pyplot as plt

contact_matrix = pd.crosstab(
    shortlist_contact_summary["ligand"],
    shortlist_contact_summary["residue"]
)

plt.figure(figsize=(12, 5))
plt.imshow(contact_matrix, aspect="auto")
plt.xticks(range(len(contact_matrix.columns)), contact_matrix.columns, rotation=90)
plt.yticks(range(len(contact_matrix.index)), contact_matrix.index)
plt.xlabel("Residue")
plt.ylabel("Ligand")
plt.title("Residue-contact heatmap for shortlisted ligands")
plt.colorbar(label="Contact count")
plt.tight_layout()
plt.show()

contact_counts = shortlist_contact_summary.groupby("ligand").size().sort_values(ascending=False)

plt.figure(figsize=(8,4))
plt.bar(contact_counts.index, contact_counts.values)
plt.xticks(rotation=45, ha="right")
plt.ylabel("Number of contacting residues")
plt.xlabel("Ligand")
plt.title("Protein-contact counts for shortlisted ligands")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,4))
plt.bar(
    interaction_comparison_df["ligand"],
    interaction_comparison_df["n_shared_with_native"]
)
plt.xticks(rotation=45, ha="right")
plt.ylabel("Number of shared residues with native ligand")
plt.xlabel("Ligand")
plt.title("Binding-site similarity to native ligand")
plt.tight_layout()
plt.show()

import pandas as pd

paper_hits = pd.read_csv("paper_hits_master_table.csv")
key_contact_df = pd.read_csv("key_residue_contacts.csv")
interaction_comparison_df = pd.read_csv("interaction_comparison_vs_native.csv")

paper_hits = paper_hits.merge(key_contact_df, on="ligand", how="left")
paper_hits = paper_hits.merge(
    interaction_comparison_df[
        ["ligand", "n_shared_with_native", "shared_residues"]
    ],
    on="ligand",
    how="left"
)

# Fix possible dnn_score naming issue after earlier merges
if "dnn_score" not in paper_hits.columns:
    if "dnn_score_x" in paper_hits.columns:
        paper_hits["dnn_score"] = paper_hits["dnn_score_x"]
    elif "dnn_score_y" in paper_hits.columns:
        paper_hits["dnn_score"] = paper_hits["dnn_score_y"]

paper_hits.to_csv("paper_hits_master_table.csv", index=False)

display_cols = [
    "ligand",
    "dnn_score",
    "vina_score_kcal_mol",
    "final_decision",
    "n_key_residues_contacted",
    "key_residues_contacted",
    "n_shared_with_native"
]

# Keep only columns that actually exist
display_cols = [col for col in display_cols if col in paper_hits.columns]

display(paper_hits[display_cols].head(15))

import pandas as pd
import matplotlib.pyplot as plt

contacts = pd.read_csv("shortlist_contact_summary.csv")

# binary contact matrix
contact_matrix = pd.crosstab(contacts["ligand"], contacts["residue"])
contact_matrix = (contact_matrix > 0).astype(int)

# sort residues by how many ligands contact them
residue_order = contact_matrix.sum(axis=0).sort_values(ascending=False).index
contact_matrix = contact_matrix[residue_order]

plt.figure(figsize=(14, 5))
plt.imshow(contact_matrix, aspect="auto")
plt.xticks(range(len(contact_matrix.columns)), contact_matrix.columns, rotation=90)
plt.yticks(range(len(contact_matrix.index)), contact_matrix.index)
plt.xlabel("Residue")
plt.ylabel("Ligand")
plt.title("Binary residue-contact map for shortlisted ligands")
plt.colorbar(label="Contact presence (0/1)")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

contacts = pd.read_csv("shortlist_contact_summary.csv")
native_contacts = pd.read_csv("native_contact_residues.csv")

native_set = set(native_contacts["residue"].tolist())

filtered = contacts[contacts["residue"].isin(native_set)].copy()

shared_matrix = pd.crosstab(filtered["ligand"], filtered["residue"])
shared_matrix = (shared_matrix > 0).astype(int)

residue_order = shared_matrix.sum(axis=0).sort_values(ascending=False).index
shared_matrix = shared_matrix[residue_order]

plt.figure(figsize=(12, 5))
plt.imshow(shared_matrix, aspect="auto")
plt.xticks(range(len(shared_matrix.columns)), shared_matrix.columns, rotation=90)
plt.yticks(range(len(shared_matrix.index)), shared_matrix.index)
plt.xlabel("Native-site residue")
plt.ylabel("Ligand")
plt.title("Shared residue contacts with the native ligand binding region")
plt.colorbar(label="Shared contact presence (0/1)")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

comp = pd.read_csv("interaction_comparison_vs_native.csv")

comp = comp.sort_values("n_shared_with_native", ascending=False)

plt.figure(figsize=(8,4))
plt.bar(comp["ligand"], comp["n_shared_with_native"])
plt.xticks(rotation=45, ha="right")
plt.ylabel("Shared contacting residues")
plt.xlabel("Ligand")
plt.title("Binding-site similarity relative to the native ligand")
plt.tight_layout()
plt.show()