# -*- coding: utf-8 -*-
"""06_ADMET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12iw34IKJRAzp1QARhmX9skyAFibDD3Hx
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from rdkit import Chem, RDLogger
from rdkit.Chem import Descriptors, Crippen, Lipinski, QED, rdMolDescriptors
from rdkit.Chem.FilterCatalog import FilterCatalog, FilterCatalogParams

RDLogger.DisableLog("rdApp.warning")

import os
import pandas as pd

paper_hits_file = "paper_hits_master_table.csv"

candidate_shortlist_files = [
    "final_paper_shortlist.csv",
    "final_paper_shortlist_with_admet.csv",
    "final_md_shortlist.csv",
    "final_md_candidates.csv",
]

shortlist_file = None
for f in candidate_shortlist_files:
    if os.path.exists(f):
        shortlist_file = f
        break

if not os.path.exists(paper_hits_file):
    raise FileNotFoundError(f"{paper_hits_file} not found")

if shortlist_file is None:
    raise FileNotFoundError("No shortlist CSV found. Checked: " + ", ".join(candidate_shortlist_files))

paper_hits = pd.read_csv(paper_hits_file)
shortlist = pd.read_csv(shortlist_file)

print("Using shortlist file:", shortlist_file)
print("paper_hits shape:", paper_hits.shape)
print("shortlist shape:", shortlist.shape)

display(shortlist)

# PAINS catalog
pains_params = FilterCatalogParams()
pains_params.AddCatalog(FilterCatalogParams.FilterCatalogs.PAINS_A)
pains_params.AddCatalog(FilterCatalogParams.FilterCatalogs.PAINS_B)
pains_params.AddCatalog(FilterCatalogParams.FilterCatalogs.PAINS_C)
PAINS_CATALOG = FilterCatalog(pains_params)

# Brenk catalog
brenk_params = FilterCatalogParams()
brenk_params.AddCatalog(FilterCatalogParams.FilterCatalogs.BRENK)
BRENK_CATALOG = FilterCatalog(brenk_params)

print("PAINS and Brenk catalogs ready.")

def keep_largest_fragment(mol):
    frags = Chem.GetMolFrags(mol, asMols=True, sanitizeFrags=True)
    if len(frags) == 0:
        return None
    return max(frags, key=lambda m: m.GetNumHeavyAtoms())


def get_alerts(mol, catalog):
    try:
        matches = catalog.GetMatches(mol)
        desc = [m.GetDescription() for m in matches]
        return len(desc), "; ".join(desc)
    except Exception:
        return 0, ""


def admet_descriptor_row(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return pd.Series([np.nan] * 24)

    mol = keep_largest_fragment(mol)
    if mol is None:
        return pd.Series([np.nan] * 24)

    mw = Descriptors.MolWt(mol)
    logp = Crippen.MolLogP(mol)
    hbd = Lipinski.NumHDonors(mol)
    hba = Lipinski.NumHAcceptors(mol)
    tpsa = Descriptors.TPSA(mol)
    rotb = Lipinski.NumRotatableBonds(mol)
    rings = rdMolDescriptors.CalcNumRings(mol)
    arom_rings = rdMolDescriptors.CalcNumAromaticRings(mol)
    heavy_atoms = mol.GetNumHeavyAtoms()
    frac_csp3 = rdMolDescriptors.CalcFractionCSP3(mol)
    mr = Crippen.MolMR(mol)
    qed = QED.qed(mol)

    pains_n, pains_desc = get_alerts(mol, PAINS_CATALOG)
    brenk_n, brenk_desc = get_alerts(mol, BRENK_CATALOG)

    # Lipinski: usually acceptable if 0 or 1 violation
    lipinski_viol = int(mw > 500) + int(logp > 5) + int(hbd > 5) + int(hba > 10)
    lipinski_pass = int(lipinski_viol <= 1)

    veber_pass = int((rotb <= 10) and (tpsa <= 140))
    egan_pass = int((logp <= 5.88) and (tpsa <= 131.6))
    ghose_pass = int((160 <= mw <= 480) and (-0.4 <= logp <= 5.6) and (20 <= heavy_atoms <= 70) and (40 <= mr <= 130))
    muegge_pass = int((200 <= mw <= 600) and (-2 <= logp <= 5) and (tpsa <= 150) and (hbd <= 5) and (hba <= 10) and (rotb <= 15) and (rings >= 1))

    # Simple CNS/BBB-friendly heuristic
    # This is only a rough screening rule, not a true BBB model
    bbb_like = int((mw <= 450) and (1 <= logp <= 5) and (tpsa <= 90) and (hbd <= 2) and (rotb <= 8))

    no_pains = int(pains_n == 0)
    no_brenk = int(brenk_n == 0)

    # Simple internal prioritization score
    admet_score = (
        lipinski_pass +
        veber_pass +
        egan_pass +
        ghose_pass +
        muegge_pass +
        no_pains +
        no_brenk +
        bbb_like +
        float(qed)
    )

    return pd.Series([
        mw, logp, hbd, hba, tpsa, rotb,
        rings, arom_rings, heavy_atoms, frac_csp3, mr, qed,
        lipinski_viol, lipinski_pass, veber_pass, egan_pass, ghose_pass, muegge_pass,
        pains_n, pains_desc, brenk_n, brenk_desc,
        bbb_like, admet_score
    ])

paper_hits[[
    "MW", "LogP", "HBD", "HBA", "TPSA", "RotB",
    "Rings", "AromaticRings", "HeavyAtoms", "FractionCSP3", "MolarRefractivity", "QED",
    "Lipinski_violations", "Lipinski_pass", "Veber_pass", "Egan_pass", "Ghose_pass", "Muegge_pass",
    "PAINS_alerts", "PAINS_details", "Brenk_alerts", "Brenk_details",
    "BBB_like", "ADMET_score"
]] = paper_hits["canonical_smiles"].apply(admet_descriptor_row)

paper_hits.to_csv("paper_hits_master_table_with_admet.csv", index=False)

display(paper_hits[[
    "ligand", "dnn_score", "vina_score_kcal_mol",
    "MW", "LogP", "TPSA", "QED",
    "Lipinski_pass", "Veber_pass", "Egan_pass", "Ghose_pass", "Muegge_pass",
    "PAINS_alerts", "Brenk_alerts", "BBB_like", "ADMET_score",
    "final_decision"
]].head(15))

def admet_comment(row):
    notes = []

    if row["BBB_like"] == 1:
        notes.append("CNS-friendly heuristic: yes")
    else:
        notes.append("CNS-friendly heuristic: no")

    if row["Lipinski_pass"] == 1 and row["Veber_pass"] == 1:
        notes.append("oral-likeness: favorable")
    else:
        notes.append("oral-likeness: limited")

    if row["PAINS_alerts"] > 0:
        notes.append("PAINS alert present")
    if row["Brenk_alerts"] > 0:
        notes.append("Brenk alert present")

    if row["TPSA"] > 90:
        notes.append("high TPSA may limit BBB")
    if row["LogP"] > 5:
        notes.append("high lipophilicity")
    if row["MW"] > 500:
        notes.append("high molecular weight")

    return " | ".join(notes)

paper_hits["ADMET_comment"] = paper_hits.apply(admet_comment, axis=1)
paper_hits.to_csv("paper_hits_master_table_with_admet.csv", index=False)

display(paper_hits[[
    "ligand", "vina_score_kcal_mol", "QED", "BBB_like", "ADMET_comment"
]].head(15))

final_candidates = paper_hits[
    paper_hits["final_decision"].isin(["keep", "maybe"])
].copy()

final_candidates["Publication_priority_score"] = (
    2.0 * final_candidates["dnn_score"] +
    0.15 * (-final_candidates["vina_score_kcal_mol"]) +
    0.20 * final_candidates["ADMET_score"]
)

final_candidates = final_candidates.sort_values("Publication_priority_score", ascending=False)
final_candidates.to_csv("final_ranked_candidates_with_admet.csv", index=False)

display(final_candidates[[
    "ligand", "dnn_score", "vina_score_kcal_mol",
    "QED", "Lipinski_pass", "Veber_pass", "Egan_pass", "Ghose_pass", "Muegge_pass",
    "PAINS_alerts", "Brenk_alerts", "BBB_like",
    "Publication_priority_score", "final_decision"
]].head(10))

final_paper_shortlist = final_candidates.head(5).copy()
final_paper_shortlist.to_csv("final_paper_shortlist_with_admet.csv", index=False)

display(final_paper_shortlist[[
    "ligand", "dnn_score", "vina_score_kcal_mol",
    "MW", "LogP", "TPSA", "QED",
    "Lipinski_pass", "Veber_pass", "Egan_pass", "Ghose_pass", "Muegge_pass",
    "PAINS_alerts", "Brenk_alerts", "BBB_like",
    "Publication_priority_score", "ADMET_comment"
]])

plot_df = final_paper_shortlist.copy()

plt.figure(figsize=(7, 5))
plt.scatter(plot_df["LogP"], plot_df["TPSA"], s=120)

for _, row in plot_df.iterrows():
    plt.text(row["LogP"], row["TPSA"], row["ligand"], fontsize=9)

plt.axhline(90, linestyle="--")
plt.axvline(5, linestyle="--")
plt.axvline(1, linestyle="--")

plt.xlabel("LogP")
plt.ylabel("TPSA (Å²)")
plt.title("ADMET-oriented positioning of final shortlisted AChE hits")
plt.tight_layout()
plt.show()

plot_df = final_paper_shortlist.sort_values("Publication_priority_score", ascending=True)

plt.figure(figsize=(8, 5))
plt.barh(plot_df["ligand"], plot_df["Publication_priority_score"])
plt.xlabel("Publication priority score")
plt.ylabel("Ligand")
plt.title("Final integrated ranking of shortlisted AChE candidates")
plt.tight_layout()
plt.show()

plot_df = final_paper_shortlist.copy()

plt.figure(figsize=(7, 5))
plt.scatter(plot_df["QED"], -plot_df["vina_score_kcal_mol"], s=120)

for _, row in plot_df.iterrows():
    plt.text(row["QED"], -row["vina_score_kcal_mol"], row["ligand"], fontsize=9)

plt.xlabel("QED")
plt.ylabel("- Vina score")
plt.title("Drug-likeness vs docking strength")
plt.tight_layout()
plt.show()

publication_table = final_paper_shortlist[[
    "ligand",
    "dnn_score",
    "vina_score_kcal_mol",
    "MW",
    "LogP",
    "TPSA",
    "HBD",
    "HBA",
    "RotB",
    "QED",
    "Lipinski_pass",
    "Veber_pass",
    "Egan_pass",
    "Ghose_pass",
    "Muegge_pass",
    "PAINS_alerts",
    "Brenk_alerts",
    "BBB_like",
    "ADMET_comment"
]].copy()

publication_table.to_csv("publication_admet_table.csv", index=False)
display(publication_table)

import os
import shutil
from google.colab import files

# Name of output zip
zip_name = "full_project_backup"

# Zip the entire current working directory
shutil.make_archive(zip_name, 'zip', root_dir='.')

print(f"Created: {zip_name}.zip")

# Download the zip file
files.download(f"{zip_name}.zip")